#!/bin/bash
# Script that runs when suspending or waking up

resume(){
	DISPLAY=:0.0 ; export DISPLAY
	su np3w -c "i3lock -c ec6b4a -u -n"
}

case $1/$2 in
	pre/*)
		echo "Going to $2"
	;;
	post/*)
		echo "Waking up from $2"
		resume
	;;
esac

exit 0

